Projekt/MojTimskiProjekt/Models/ProslaStanja.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MojTimskiProjekt.Models
{
    public partial class ProslaStanja
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public DateTime DatumOd { get; set; }
        public DateTime DatumDo { get; set; }
        public string Opis { get; set; }
        public int? IdAutoceste { get; set; }
        public int? IdDionice { get; set; }

        public Autocesta IdAutocesteNavigation { get; set; }
        public Dionica IdDioniceNavigation { get; set; }
    }
}

Projekt/MojTimskiProjekt/Controllers/ProslaStanjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MojTimskiProjekt.Extensions;
using MojTimskiProjekt.Models;
using Newtonsoft.Json;

namespace MojTimskiProjekt.Controllers
{
    public class ProslaStanjaController : Controller
    {
        private readonly RPPP14Context _context;
        private readonly AppSettings appData;
        private readonly ILogger logger;

        public ProslaStanjaController(RPPP14Context context, IOptionsSnapshot<AppSettings> options, ILogger<UpraviteljController> logger)
        {
            _context = context;
            appData = options.Value;
            this.logger = logger;
        }

        // GET: ProslaStanja
        public async Task<IActionResult> Index()
        {
            var rPPP14Context = _context.ProslaStanja.Include(d => d.IdAutocesteNavigation).Include(p => p.IdDioniceNavigation);
            return View(await rPPP14Context.ToListAsync());
        }

        // GET: ProslaStanja/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proslaStanja = await _context.ProslaStanja
                .Include(p => p.IdAutocesteNavigation)
                .Include(p => p.IdDioniceNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proslaStanja == null)
            {
                return NotFound();
            }

            return View(proslaStanja);
        }

        // GET: ProslaStanja/Create
        public IActionResult Create()
        {
            ViewData["IdAutoceste"] = new SelectList(_context.Autocesta, "Id", "Kraj");
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj");
            return View();
        }

        // POST: ProslaStanja/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DatumOd,DatumDo,Opis,IdAutoceste,IdDionice")] ProslaStanja proslaStanja)
        {
            logger.LogTrace(JsonConvert.SerializeObject(proslaStanja));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(proslaStanja);
                    await _context.SaveChangesAsync();
                    ViewData["message"] = $"Stanje {proslaStanja.Opis} je dodano u bazu";
                    logger.LogInformation(new EventId(1000), $"Stanje {proslaStanja.Opis} je dodano u bazu");
                    return RedirectToAction(nameof(Index), ViewData["message"]);
                }
                catch (Exception exc)
                {
                    logger.LogError("Pogreška prilikom dodavanje novog stanja: {0}", exc.CompleteExceptionMessage());
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return View(proslaStanja);
                }
            }
            ViewData["IdAutoceste"] = new SelectList(_context.Autocesta, "Id", "Kraj", proslaStanja.IdAutoceste);
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", proslaStanja.IdDionice);
            return View(proslaStanja);
        }

        // GET: ProslaStanja/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proslaStanja = await _context.ProslaStanja.FindAsync(id);
            if (proslaStanja == null)
            {
                return NotFound();
            }
            ViewData["IdAutoceste"] = new SelectList(_context.Autocesta, "Id", "Kraj", proslaStanja.IdAutoceste);
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", proslaStanja.IdDionice);
            return View(proslaStanja);
        }

        // POST: ProslaStanja/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DatumOd,DatumDo,Opis,IdAutoceste,IdDionice")] ProslaStanja proslaStanja)
        {
            if (id != proslaStanja.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proslaStanja);
                    await _context.SaveChangesAsync();
                    logger.LogInformation(new EventId(1000), $"Stanje {proslaStanja.Opis} je uspješno ažurirano");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProslaStanjaExists(proslaStanja.Id))
                    {
                        logger.LogError("Pogreška prilikom ažuriranja stanja: {0}");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAutoceste"] = new SelectList(_context.Autocesta, "Id", "Kraj", proslaStanja.IdAutoceste);
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", proslaStanja.IdDionice);
            return View(proslaStanja);
        }

        // GET: ProslaStanja/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proslaStanja = await _context.ProslaStanja
                .Include(p => p.IdAutocesteNavigation)
                .Include(p => p.IdDioniceNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proslaStanja == null)
            {
                return NotFound();
            }

            return View(proslaStanja);
        }

        // POST: ProslaStanja/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proslaStanja = await _context.ProslaStanja.FindAsync(id);
            _context.ProslaStanja.Remove(proslaStanja);
            await _context.SaveChangesAsync();
            logger.LogInformation(new EventId(1000), $"Stanje {proslaStanja.Opis} je uspješno obrisano");
            return RedirectToAction(nameof(Index));
        }

        private bool ProslaStanjaExists(int id)
        {
            return _context.ProslaStanja.Any(e => e.Id == id);
        }
    }
}

Projekt/MojTimskiProjekt/Views/ProslaStanja/Create.cshtml
@model MojTimskiProjekt.Models.ProslaStanja

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodavanje novog stanja na autocesti</h2>

<h3>Stanje na autocesti</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DatumOd" class="control-label">Datum od</label>
                <input asp-for="DatumOd" class="form-control" />
                <span asp-validation-for="DatumOd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumDo" class="control-label">Datum do</label>
                <input asp-for="DatumDo" class="form-control" />
                <span asp-validation-for="DatumDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAutoceste" class="control-label">Autocesta</label>
                <select asp-for="IdAutoceste" class="form-control" asp-items="ViewBag.IdAutoceste"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdDionice" class="control-label">Izlaz</label>
                <select asp-for="IdDionice" class="form-control" asp-items="ViewBag.IdDionice"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div class="col-md-5">
    <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Index">Natrag na Listu</a>
</div>

Projekt/MojTimskiProjekt/Views/ProslaStanja/Delete.cshtml
@model MojTimskiProjekt.Models.ProslaStanja

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brisanje</h2>

<div>
    <h3>Stanje na autocesti</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatumOd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatumOd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatumDo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatumDo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdAutocesteNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdAutocesteNavigation.Kraj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdDioniceNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdDioniceNavigation.Kraj)
        </dd>
    </dl>

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <form asp-action="Delete" onclick="return confirm('Jeste li sigurni da želite obrisati?')">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Obriši" class="btn btn-danger delete" /> |
                </form>
            </div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Index">Natrag na listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/ProslaStanja/Details.cshtml
@model MojTimskiProjekt.Models.ProslaStanja

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalji</h2>

<div>
    <h3>Stanje na autocesti</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatumOd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatumOd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatumDo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatumDo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdAutocesteNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdAutocesteNavigation.Kraj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdDioniceNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdDioniceNavigation.Kraj)
        </dd>
    </dl>
</div>
<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-action="Edit" asp-route-id="@Model.Id">Uredi</a>
            </div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Index">Natrag na Listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/ProslaStanja/Edit.cshtml
@model MojTimskiProjekt.Models.ProslaStanja

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Uređivanje</h2>

<h3>Stanje na autocesti</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DatumOd" class="control-label"></label>
                <input asp-for="DatumOd" class="form-control" />
                <span asp-validation-for="DatumOd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumDo" class="control-label"></label>
                <input asp-for="DatumDo" class="form-control" />
                <span asp-validation-for="DatumDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAutoceste" class="control-label"></label>
                <select asp-for="IdAutoceste" class="form-control" asp-items="ViewBag.IdAutoceste"></select>
                <span asp-validation-for="IdAutoceste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDionice" class="control-label"></label>
                <select asp-for="IdDionice" class="form-control" asp-items="ViewBag.IdDionice"></select>
                <span asp-validation-for="IdDionice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Index">Natrag na Listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/ProslaStanja/Index.cshtml
@model IEnumerable<MojTimskiProjekt.Models.ProslaStanja>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>
<h3>Stanja na autocestama</h3>
<br />

<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Create">Dodaj novo stanje</a>
            </div>
        </div>
    </div>
</div>

<div class="row ">
    <div class="col-md-8">

    </div>

    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="ProslaStanjaPdf">Ispis u pdf</a>
    </div>
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="ProslaStanjaExcel">Ispis u excel</a>
    </div>
</div>


<div class="jumbotron">
    <table class="table" id="proslaStanjaTable">
        <thead>
            <tr>
                <th>
                    Datum od
                </th>
                <th>
                    Datum do
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Opis)
                </th>
                <th>
                    Autocesta
                </th>
                <th>
                    Dionica
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumOd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumDo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Opis)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAutocesteNavigation.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdDioniceNavigation.Naziv)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section scripts{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#proslaStanjaTable').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        });
    </script>
}