Projekt/MojTimskiProjekt/Models/Autocesta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MojTimskiProjekt.Models
{
    public partial class Autocesta
    {
        public Autocesta()
        {
            Dionica = new HashSet<Dionica>();
            Obavijest = new HashSet<Obavijest>();
            ProslaStanja = new HashSet<ProslaStanja>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Naziv je obavezan")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Duljina je obavezna")]
        public double DuljinaPlan { get; set; }
        [Required(ErrorMessage = "Duljina je obavezna")]
        public double Duljina { get; set; }
        [Required(ErrorMessage = "Pocetak je obavezan")]
        public string Pocetak { get; set; }
        [Required(ErrorMessage = "Kraj je obavezan")]
        public string Kraj { get; set; }
        [Required(ErrorMessage = "upravitelj je obavezan")]
        public int IdUpravitelja { get; set; }

        public Upravitelj IdUpraviteljaNavigation { get; set; }
        public ICollection<Dionica> Dionica { get; set; }
        public ICollection<Obavijest> Obavijest { get; set; }
        public ICollection<ProslaStanja> ProslaStanja { get; set; }
    }
}

Projekt/MojTimskiProjekt/ViewModels/AutocestaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using MojTimskiProjekt.Models;

namespace MojTimskiProjekt.ViewModels
{
    public class AutocestaViewModel
    {
        public int Id { get; set; }

        public string Naziv { get; set; }
       
        public double DuljinaPlan { get; set; }
  
        public double Duljina { get; set; }
       
        public string Pocetak { get; set; }
      
        public string Kraj { get; set; }
    
        public int IdUpravitelja { get; set; }

      
       
    }
}

Projekt/MojTimskiProjekt/Areas/Autocomplete/Controllers/AutocestaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MojTimskiProjekt.Areas.Autocomplete.Models;
using MojTimskiProjekt.Models;
namespace MojTimskiProjekt.Areas.Autocomplete.Controllers
{

    [Route("autocomplete/Autocesta")]
    public class AutocestaController : Controller
    {
        private readonly RPPP14Context ctx;
        private readonly AppSettings appData;

        public AutocestaController(RPPP14Context ctx, IOptionsSnapshot<AppSettings> options)
        {
            this.ctx = ctx;
            appData = options.Value;
        }

        [HttpGet]
        public IEnumerable<IdLabel> Get(string term)
        {
            var query = ctx.Autocesta
                            .Select(m => new IdLabel
                            {
                                Id = m.IdUpravitelja,
                                Label = m.IdUpraviteljaNavigation.Naziv
                            })
                            .Where(l => l.Label.Contains(term));

            var list = query.OrderBy(l => l.Label)
                            .ThenBy(l => l.Id)
                            .Take(appData.AutoCompleteCount)
                            .ToList();
            return list;
        }
    }
}

Projekt/MojTimskiProjekt/Controllers/AutocestaController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using MojTimskiProjekt.Extensions;
using MojTimskiProjekt.Models;
using MojTimskiProjekt.ViewModels;

namespace MojTimskiProjekt.Controllers
{
    public class AutocestaController : Controller
    {
        private readonly RPPP14Context _context;
  
        private readonly ILogger logger;

        public AutocestaController(RPPP14Context context, ILogger<AutocestaController> logger)
        {
            _context = context;
            this.logger = logger;
        }


        public IActionResult Karta()
        {
            return View();
        }


        // GET: Autocesta
        public async Task<IActionResult> Index()
        {   
            var rPPP14Context = _context.Autocesta.Include(a => a.IdUpraviteljaNavigation);
            var dionice = _context.Dionica
                   .OrderBy(d => d.Naziv)
                   .Select(d => new { d.Naziv, d.IdAutoceste })
                   .ToList();
            ViewData["Dionice"] = dionice;

            
            return View(await rPPP14Context.ToListAsync());
        }
        private void GetDionice()
        {
            var dionice = _context.Dionica
                   .OrderBy(d => d.Naziv)
                   .Select(d => new { d.Naziv, d.IdAutoceste })
                   .ToList();
            ViewBag.Dionice = new SelectList(dionice, nameof(Dionica.Naziv), nameof(Dionica.IdAutoceste));
            ViewData["Dionice"] = dionice;
            
        }


        public IActionResult IndexSimple()
        {
            var autoceste = _context.Autocesta
                .AsNoTracking()
                .Include(a => a.IdUpraviteljaNavigation)
                .ToList();
            var dionice = _context.Dionica
                    .AsNoTracking()
                    
                    .ToList();

            ViewData["dionice"] = dionice;
            return View(autoceste);
        }

        public IActionResult IndexSimple2()
        {
            var autoceste = _context.Autocesta
                .AsNoTracking()
                .Select(m => new AutocestaViewModel
                {
                    Id = m.Id,
                    Naziv = m.Naziv,
                    DuljinaPlan = m.DuljinaPlan,
                    Duljina = m.Duljina,
                    Pocetak = m.Pocetak,
                    Kraj = m.Kraj,
                    IdUpravitelja = m.IdUpraviteljaNavigation.Id
                })
                .ToList();
            var model = new AutocesteViewModel
            {
                Autoceste = autoceste
            };
            var dionice = _context.Dionica
                    .AsNoTracking()
                    .ToList();

            ViewData["dionice"] = dionice;

           // logger.LogInformation("Učitavanje podataka o autocestama");
            return View(model);
        }


        // GET: Autocesta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autocesta = await _context.Autocesta
                .Include(a => a.IdUpraviteljaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autocesta == null)
            {
                return NotFound();
            }

            return View(autocesta);
        }

        // GET: Autocesta/Create
        public IActionResult Create()
        {
            ViewData["IdUpravitelja"] = new SelectList(_context.Upravitelj, "Id", "Naziv");
            return View();
        }

        // POST: Autocesta/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("Id,Naziv,DuljinaPlan,Duljina,Pocetak,Kraj,IdUpravitelja")] Autocesta autocesta)
        {

            logger.LogTrace(JsonConvert.SerializeObject(autocesta));
            if (ModelState.IsValid && !AutocestaExists(autocesta.Id))
            {
                try
                {
                    _context.Add(autocesta);
                    await _context.SaveChangesAsync();
                    ViewData["message"] = $"Autocesta {autocesta.Naziv} je dodana u bazu";

                    logger.LogInformation(new EventId(1000), $"Autocesta {autocesta.Naziv} je dodana u bazu");
                    return RedirectToAction("IndexSimple2", ViewData["message"]);
                }catch (Exception exc)
                {
                   
                    logger.LogError("Pogreška prilikom dodavanje nove autoceste: {0}", exc.CompleteExceptionMessage());
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return View(autocesta);
                }

            }

            else
            {
                ViewData["IdUpravitelja"] = new SelectList(_context.Upravitelj, "Id", "Naziv", autocesta.IdUpravitelja);
                return View(autocesta);

            }



        }

        // GET: Autocesta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autocesta = await _context.Autocesta.FindAsync(id);
            if (autocesta == null)
            {
                return NotFound();
            }
            ViewData["IdUpravitelja"] = new SelectList(_context.Upravitelj, "Id", "Naziv", autocesta.IdUpravitelja);
            return View(autocesta);
        }


        // POST: Autocesta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,DuljinaPlan,Duljina,Pocetak,Kraj,IdUpravitelja")] Autocesta autocesta)
        {
            if (id != autocesta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autocesta);
                    await _context.SaveChangesAsync();

                    logger.LogInformation($"Autocesta {autocesta.Naziv} je ažurirana");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutocestaExists(autocesta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUpravitelja"] = new SelectList(_context.Upravitelj, "Id", "Naziv", autocesta.IdUpravitelja);
            return View(autocesta);
        }


        [HttpGet]
        public IActionResult EditPartial(int id)
        {
            var autocesta = _context.Autocesta
                             .AsNoTracking()
                             .Where(m => m.Id == id)
                             .SingleOrDefault();
            if (autocesta != null)
            {
              
                return PartialView(autocesta);
            }
            else
            {
                return NotFound($"Neispravan id autoceste: {id}");
            }
        }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult EditPartial(Autocesta autocesta)
    {
        if (autocesta == null)
        {
            return NotFound("Nema poslanih podataka");
        }
        bool checkId = _context.Autocesta.Any(m => m.Id == autocesta.Id);
        if (!checkId)
        {
            return NotFound($"Neispravan id autoceste: {autocesta.Id}");
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(autocesta);
               _context.SaveChanges();
                logger.LogInformation(new EventId(1000), $"Autocesta {autocesta.Naziv} je ažurirana");
                return StatusCode(302, Url.Action(nameof(Row), new { id = autocesta.Id }));
                 
               }
            catch (Exception exc)
            {
                ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                return PartialView(autocesta);
            }
        }
        else
        {
            return PartialView(autocesta);
        }
    }


        public PartialViewResult Row(int id)
        {
            var autocesta = _context.Autocesta
                             .Where(m => m.Id == id)
                             .Select(m => new AutocestaViewModel
                             {
                                 Id = m.Id,
                                 Naziv = m.Naziv,
                                 DuljinaPlan = m.DuljinaPlan,
                                 Duljina = m.Duljina,
                                 Pocetak = m.Pocetak,
                                 Kraj = m.Kraj,
                                 IdUpravitelja = m.IdUpraviteljaNavigation.Id
               
                             })
                             .SingleOrDefault();
            if (autocesta != null)
            {
                return PartialView(autocesta);
            }
            else
            {
                //vratiti prazan sadržaj?
                return PartialView("ErrorMessageRow", $"Neispravan id autoceste: {id}");
            }
        }





        // GET: Autocesta/Delete/5

Projekt/MojTimskiProjekt/Views/Autocesta/Create.cshtml
@model MojTimskiProjekt.Models.Autocesta

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Autocesta</h4>
<hr />
<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        
        <div class="form-group">
            <label asp-for="Naziv" class="control-label"></label>
            <input asp-for="Naziv" class="form-control" />
            <span asp-validation-for="Naziv" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DuljinaPlan" class="control-label"></label>
            <input asp-for="DuljinaPlan" class="form-control" />
            <span asp-validation-for="DuljinaPlan" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Duljina" class="control-label"></label>
            <input asp-for="Duljina" class="form-control" />
            <span asp-validation-for="Duljina" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Pocetak" class="control-label"></label>
            <input asp-for="Pocetak" class="form-control" />
            <span asp-validation-for="Pocetak" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Kraj" class="control-label"></label>
            <input asp-for="Kraj" class="form-control" />
            <span asp-validation-for="Kraj" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IdUpravitelja" class="control-label"></label>
            <select asp-for="IdUpravitelja" class="form-control" asp-items="ViewBag.IdUpravitelja"></select>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Dodaj" class="btn btn-success btn-lg" />
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
        </form>
    </div>
</div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekt/MojTimskiProjekt/Views/Autocesta/Delete.cshtml
@model MojTimskiProjekt.Models.Autocesta

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Autocesta</h4>
    <hr />
    <div class="jumbotron">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DuljinaPlan)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DuljinaPlan)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Duljina)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Duljina)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Pocetak)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Pocetak)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Kraj)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Kraj)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.IdUpraviteljaNavigation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IdUpraviteljaNavigation.Naziv)
            </dd>
        </dl>
    </div>
    <form asp-action="Delete" onclick="return confirm('Are you sure you want to delete?')">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger delete" id="delete" /> |

    </form>
     
</div>

Projekt/MojTimskiProjekt/Views/Autocesta/Details.cshtml
@model MojTimskiProjekt.Models.Autocesta

@{
    ViewData["Title"] = "Details";
}

<h2>Detalji</h2>

<div >
    <h4>Autocesta</h4>
    <hr />
    <dl class="dl-horizontal jumbotron">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DuljinaPlan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DuljinaPlan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duljina)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duljina)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pocetak)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pocetak)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Kraj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Kraj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdUpraviteljaNavigation.Naziv) Upravitelja
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdUpraviteljaNavigation.Naziv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Projekt/MojTimskiProjekt/Views/Autocesta/Edit.cshtml
@model MojTimskiProjekt.Models.Autocesta

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<div class="jumbotron">
    <h4>Autocesta</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Naziv" class="control-label"></label>
                    <input asp-for="Naziv" class="form-control" />
                    <span asp-validation-for="Naziv" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DuljinaPlan" class="control-label"></label>
                    <input asp-for="DuljinaPlan" class="form-control" />
                    <span asp-validation-for="DuljinaPlan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Duljina" class="control-label"></label>
                    <input asp-for="Duljina" class="form-control" />
                    <span asp-validation-for="Duljina" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Pocetak" class="control-label"></label>
                    <input asp-for="Pocetak" class="form-control" />
                    <span asp-validation-for="Pocetak" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Kraj" class="control-label"></label>
                    <input asp-for="Kraj" class="form-control" />
                    <span asp-validation-for="Kraj" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IdUpravitelja" class="control-label"></label>
                    <select asp-for="IdUpravitelja" class="form-control" asp-items="ViewBag.IdUpravitelja"></select>
                    <span asp-validation-for="IdUpravitelja" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success btn-lg" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekt/MojTimskiProjekt/Views/Autocesta/Index.cshtml
@model IEnumerable<MojTimskiProjekt.Models.Autocesta>

@{
    ViewData["Title"] = "Index";
}

<h2>Autoceste</h2>

<p>@ViewData["message"]</p>
<div class="jumbotron">
    <div class="row">
        <div class="dropdown col-md-5">
            <a class="btn btn-lg btn-primary  btn-block"   asp-area="" asp-controller="Dionica" asp-action="Index" >
                Dionice
            </a>
            
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Autocesta" asp-action="Create">Dodaj autocestu</a>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Autocesta" asp-action="IndexSimple">Master-detail</a>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Autocesta" asp-action="IndexSimple2">Uredi autoceste</a>
        </div>
    </div>
    


</div>
<div class="jumbotron">


    <table class="table" id="autocestaTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DuljinaPlan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Duljina)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pocetak)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kraj)
                </th>
                <th>
                    Naziv upravitelja
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DuljinaPlan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duljina)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pocetak)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kraj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdUpraviteljaNavigation.Naziv)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#autocestaTable').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        });
    </script>
}

Projekt/MojTimskiProjekt/Views/Autocesta/IndexSimple.cshtml
@using MojTimskiProjekt.Models
@model IEnumerable<MojTimskiProjekt.Models.Autocesta>

@{
    ViewData["Title"] = "IndexSimple";
    IEnumerable<Dionica> dionice = ViewData["dionice"] as IEnumerable<Dionica>;
}

<p></p>

<br />

    <div class="row">
        <div class="dropdown col-md-3">
            <a class="btn btn-lg btn-primary  btn-block" type="button" asp-area="" asp-controller="Dionica" asp-action="Index">
                Dionice
            </a>

        </div>
    </div>
<br />
    <div class="row">

        <div class="col-md-3">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Autocesta" asp-action="IndexSimple2">Uredi autoceste</a>
        </div>
    </div>




<div class="row ">

    <div class="col-md-8">
       
    </div>
  
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="AutocestePdf">Ispis u pdf</a>
    </div>
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="AutocesteExcel">Ispis u excel</a>
    </div>

</div>

<div class="jumbotron">


    <table class="table" id="autocestaTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    Dionice

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Duljina)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pocetak)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kraj)
                </th>
                <th>
                    Naziv upravitelja
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @{
                            foreach (Dionica dionica in dionice)
                            {
                                if (dionica != null && dionica.IdAutoceste == item.Id)
                                {

                                    @Html.DisplayFor(modelItem => dionica.Naziv)

                                    <br />

                                }

                            }
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duljina)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pocetak)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kraj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdUpraviteljaNavigation.Naziv)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Projekt/MojTimskiProjekt/Views/Autocesta/IndexSimple2.cshtml
@using MojTimskiProjekt.Models
@model MojTimskiProjekt.ViewModels.AutocesteViewModel

@{
    ViewData["Title"] = "IndexSimple";
    IEnumerable<Dionica> dionice = ViewData["dionice"] as IEnumerable<Dionica>;
}
<p></p>

<h3>Prikaz autocesta s pripadajućim dionicama</h3>

<br />

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-primary" asp-controller="Autocesta" asp-action="Create">Dodaj autocestu</a>
    </div>
</div>
<div class="jumbotron">



    <table class="table table-sm table-striped table-hover">
        <thead>
            <tr>
                @{
                    string[] nazivi = { "Naziv", "Duljina Plan", "Duljina", "Početak", "Kraj", "IdUpravitelja", "Dionice" };
                    for (int i = 1; i <= nazivi.Length; i++)
                    {
                        <th>
                            
                                @nazivi[i - 1]
                          
                        </th>
                    }
                }
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var autocesta in Model.Autoceste)
            {
                <partial name="Row" model="autocesta" />
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
            SetEditAjax(".editajax", '@Url.Action("EditPartial")','idautoceste');
            SetDeleteAjax(".deleteajax", '@Url.Action("DeletePartial")', 'idautoceste');
        });
    </script>
    
    
}