Projekt/MojTimskiProjekt/Areas/Autocomplete/Models/Objekt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace MojTimskiProjekt.Areas.Autocomplete.Models
{
    [DataContract]
    public class Objekt
    {
        [DataMember(Name = "label")]
        public string Label { get; set; }
        [DataMember(Name = "id")]
        public int Id { get; set; }
        public Objekt() { }
        public Objekt(int id, string label)
        {
            Id = id;
            Label = label;
        }
    }
}

Projekt/MojTimskiProjekt/Models/Objekt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MojTimskiProjekt.Models
{
    public partial class Objekt
    {
        public Objekt()
        {
            Uredaj = new HashSet<Uredaj>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    

        [Required(ErrorMessage = "Naziv je obvezno polje")]
        [Display(Name = "Naziv objekta", Prompt ="Unesite naziv objekta")]
        public string Naziv { get; set; }

        [Required(ErrorMessage = "Lokacija je obvezno polje")]
        [Display(Name = "Lokacija objekta", Prompt = "Unesite lokaciju objekta")]
        public string Lokacija { get; set; }

        
        public int IdDionice { get; set; }
        public int? IdVrsteObjekta { get; set; }

        public Dionica IdDioniceNavigation { get; set; }
        public VrstaObjekta IdVrsteObjektaNavigation { get; set; }
        public ICollection<Uredaj> Uredaj { get; set; }
    }
}

Projekt/MojTimskiProjekt/ViewModels/ObjektViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MojTimskiProjekt.ViewModels
{
    public class ObjektViewModel
    {
        public int Id { get; set; }

        public string Naziv { get; set; }

        public string Lokacija { get; set; }

        public int IdDionice { get; set; }

        public int? IdVrsteObjekta { get; set; }
    }
}

Projekt/MojTimskiProjekt/Areas/Autocomplete/Controllers/ObjektController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MojTimskiProjekt.Areas.Autocomplete.Models;
using MojTimskiProjekt.Models;

namespace MojTimskiProjekt.Areas.Autocomplete.Controllers
{

    [Route("autocomplete/Objekt")]
    public class ObjektController : Controller
    {
        private readonly RPPP14Context ctx;
        private readonly AppSettings appData;

        public ObjektController(RPPP14Context ctx, IOptionsSnapshot<AppSettings> options)
        {
            this.ctx = ctx;
            appData = options.Value;
        }

        [HttpGet]
        public IEnumerable<IdLabel> Get(string term)
        {
            var query = ctx.Objekt
            .Select(m => new IdLabel
            {
                Id = m.Id,
                Label = m.Naziv
            })
            .Where(l => l.Label.Contains(term));

            var list = query.OrderBy(l => l.Label)
            .ThenBy(l => l.Id)
            .Take(appData.AutoCompleteCount)
            .ToList();
            return list;
        }
    }
}

Projekt/MojTimskiProjekt/Controllers/ObjektController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;
using MojTimskiProjekt.Extensions;
using MojTimskiProjekt.Models;
using MojTimskiProjekt.ViewModels;

namespace MojTimskiProjekt.Controllers
{
    public class ObjektController : Controller
    {
        private readonly RPPP14Context _context;
        private readonly AppSettings appData;
        private readonly ILogger logger;

        public ObjektController(RPPP14Context context, IOptionsSnapshot<AppSettings> options, ILogger<ObjektController> logger)
        {
            _context = context;
            appData = options.Value;
            this.logger = logger;
        }

        // GET: Objekt
        public async Task<IActionResult> Index()
        {
            var rPPP14Context = _context.Objekt
                                            .Include(a => a.IdDioniceNavigation)
                                            .Include(o => o.IdVrsteObjektaNavigation);
            var objekti = _context.Objekt
                                    .OrderBy(d => d.Naziv)
                                    .Select(d => new { d.Naziv, d.Id })
                                    .ToList();
            ViewData["Objekti"] = objekti;
            ViewBag.IdDionice = new SelectList(objekti, nameof(Objekt.IdDionice), nameof(Objekt.IdVrsteObjekta));
            return View(await rPPP14Context.ToListAsync());
        }


        public IActionResult IndexSimple()
        {
            var objekti = _context.Objekt
                .Include(o => o.IdDioniceNavigation)
                .Include(o => o.IdVrsteObjektaNavigation)
                .AsNoTracking()
                .Select(m => new ObjektViewModel
                {
                    Id = m.Id,
                    Naziv = m.Naziv,
                    Lokacija = m.Lokacija,
                    IdDionice = m.IdDionice,
                    IdVrsteObjekta = m.IdVrsteObjekta
                })
                .ToList();
            var model = new ObjektiViewModel
            {
                Objekti = objekti
            };
            ViewData["objekti"] = objekti;
            logger.LogInformation("Učitavanje podataka o objektima");
            return View(model);
        }



        public IActionResult IndexSimple2()
        {
            var objekti = _context.Objekt
                .AsNoTracking()
                .Include(a => a.IdDioniceNavigation)
                .Include(a => a.IdVrsteObjektaNavigation)
                .OrderBy(a => a.Id)
                .ToList();
            var uredaji = _context.Uredaj
                    .AsNoTracking()
                    .OrderBy(a => a.Naziv)
                    .ToList();

            ViewData["uredaji"] = uredaji;
            return View(objekti);
        }



        // GET: Objekt/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objekt = await _context.Objekt
                .Include(o => o.IdDioniceNavigation)
                .Include(o => o.IdVrsteObjektaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objekt == null)
            {
                return NotFound();
            }

            return View(objekt);
        }

        // GET: Objekt/Create
        public IActionResult Create()
        {
            var objekti = _context.Objekt
                                    .OrderBy(d => d.Naziv)
                                    .Select(d => new { d.Naziv, d.Id })
                                    .ToList();
            ViewData["Objekti"] = objekti;
            ViewBag.IdDionice = new SelectList(objekti, nameof(Objekt.IdDionice), nameof(Objekt.IdVrsteObjekta));
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj");
            ViewData["IdVrsteObjekta"] = new SelectList(_context.VrstaObjekta, "Id", "Vrsta");
            ViewData["IdObjekta"] = new SelectList(_context.Objekt, "Id", "Naziv");
            return View();
        }

        // POST: Objekt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Lokacija,IdDionice,IdVrsteObjekta")] Objekt objekt)
        {
            logger.LogTrace(JsonConvert.SerializeObject(objekt));
            if (ModelState.IsValid && !ObjektExists(objekt.Id))
            {
                try
                {
                    _context.Add(objekt);
                    await _context.SaveChangesAsync();
                    ViewData["message"] = $"Objekt {objekt.Naziv} je dodan u bazu";
                    logger.LogInformation(new EventId(1000), $"Objekt {objekt.Naziv} je dodan u bazu");
                    return RedirectToAction(nameof(Index), ViewData["message"]);
                }
                catch(Exception exc)
                {

                    logger.LogError("Pogreška prilikom dodavanje novog objekta: {0}", exc.CompleteExceptionMessage());
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return View(objekt);
                }


            }
            else
            {
                ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", objekt.IdDionice);
                ViewData["IdVrsteObjekta"] = new SelectList(_context.VrstaObjekta, "Id", "Vrsta", objekt.IdVrsteObjekta);

                /*ViewData["IdObjekta"] = new SelectList(_context.Objekt, "Id", "Naziv", objekt.Id);
                ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", objekt.IdDionice);
                ViewData["IdVrsteObjekta"] = new SelectList(_context.VrstaObjekta, "Id", "Vrsta", objekt.IdVrsteObjekta);*/
                return View(objekt);
            }
        }

        // GET: Objekt/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objekt = await _context.Objekt.FindAsync(id);
            if (objekt == null)
            {
                return NotFound();
            }
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", objekt.IdDionice);
            ViewData["IdVrsteObjekta"] = new SelectList(_context.VrstaObjekta, "Id", "Vrsta", objekt.IdVrsteObjekta);
            return View(objekt);
        }

        // POST: Objekt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Lokacija,IdDionice,IdVrsteObjekta")] Objekt objekt)
        {
            if (id != objekt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(objekt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObjektExists(objekt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDionice"] = new SelectList(_context.Dionica, "Id", "Kraj", objekt.IdDionice);
            ViewData["IdVrsteObjekta"] = new SelectList(_context.VrstaObjekta, "Id", "Vrsta", objekt.IdVrsteObjekta);
            return View(objekt);
        }

        // GET: Objekt/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objekt = await _context.Objekt
                .Include(o => o.IdDioniceNavigation)
                .Include(o => o.IdVrsteObjektaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objekt == null)
            {
                return NotFound();
            }

            return View(objekt);
        }

        // POST: Objekt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var objekt = await _context.Objekt.FindAsync(id);
            if (objekt != null)
            {
                try
                {
                    _context.Objekt.Remove(objekt);
                    await _context.SaveChangesAsync();
                    logger.LogInformation($"Objekt {objekt.Naziv} uspješno obrisan");
                } 
                catch (Exception exc)
                {
                    logger.LogError("Pogreška prilikom brisanja objekta: " + exc.CompleteExceptionMessage());
                }
            }
            else
            {
                logger.LogWarning("Ne postoji objekt s id-em: {0} ", id);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ObjektExists(int id)
        {
            return _context.Objekt.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult EditPartial(int id)
        {

Projekt/MojTimskiProjekt/Views/Objekt/Create.cshtml
@model MojTimskiProjekt.Models.Objekt

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div class="jumbotron">
    <h4>Objekt</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Naziv" class="control-label"></label>
            <input asp-for="Naziv" class="form-control" />
            <span asp-validation-for="Naziv" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Lokacija" class="control-label"></label>
            <input asp-for="Lokacija" class="form-control" />
            <span asp-validation-for="Lokacija" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IdDionice" class="control-label"></label>
            <select asp-for="IdDionice" class="form-control" asp-items="ViewBag.IdDionice"></select>
        </div>
        <div class="form-group">
            <label asp-for="IdVrsteObjekta" class="control-label"></label>
            <select asp-for="IdVrsteObjekta" class="form-control" asp-items="ViewBag.IdVrsteObjekta"></select>
        </div>
        <div class="form-group">
            <input type="submit" value="Dodaj" class="btn btn-success btn-lg " />
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
        </form>
    </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekt/MojTimskiProjekt/Views/Objekt/Delete.cshtml
@model MojTimskiProjekt.Models.Objekt

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Objekt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lokacija)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdDioniceNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdDioniceNavigation.Kraj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdVrsteObjektaNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdVrsteObjektaNavigation.Vrsta)
        </dd>
    </dl>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <form asp-action="Delete" onclick="return confirm('Are you sure you want to delete?')">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-danger delete" /> |
                </form>
            </div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Index">Natrag na listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/Objekt/Details.cshtml
@model MojTimskiProjekt.Models.Objekt

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div >
    <h4>Objekt</h4>
    <hr />
    <div class="jumbotron">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Lokacija)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lokacija)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.IdDioniceNavigation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IdDioniceNavigation.Kraj)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.IdVrsteObjektaNavigation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IdVrsteObjektaNavigation.Vrsta)
            </dd>
        </dl>
        </div>
    </div>
    <div>
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-5">
                    <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                </div>
                <div class="col-md-5">
                    <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Index">Natrag na Listu</a>
                </div>
            </div>
        </div>
    </div>

Projekt/MojTimskiProjekt/Views/Objekt/Edit.cshtml
@model MojTimskiProjekt.Models.Objekt

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Objekt</h4>
<hr />
 <div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lokacija" class="control-label"></label>
                <input asp-for="Lokacija" class="form-control" />
                <span asp-validation-for="Lokacija" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDionice" class="control-label"></label>
                <select asp-for="IdDionice" class="form-control" asp-items="ViewBag.IdDionice"></select>
                <span asp-validation-for="IdDionice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdVrsteObjekta" class="control-label"></label>
                <select asp-for="IdVrsteObjekta" class="form-control" asp-items="ViewBag.IdVrsteObjekta"></select>
                <span asp-validation-for="IdVrsteObjekta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success btn-lg" />
            </div>
        </form>
    </div>
</div>
<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Index">Natrag na Listu</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekt/MojTimskiProjekt/Views/Objekt/Index.cshtml
@model IEnumerable<MojTimskiProjekt.Models.Objekt>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Objekti</h2>
<br />


<!--div class="jumbotron">
    <div class="row">
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Zaposlenik" asp-action="Index">Zaposlenici</a>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Index">Objekti</a>
        </div>
    </div>
    <p></p>
    <div class="row">
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="ProslaStanja" asp-action="Index">Stanja</a>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="" asp-action="Index">Karta</a>
        </div>
    </div>
</div>-->

<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Create">Dodaj novi objekt</a>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="IndexSimple">Uredi objekte</a>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="IndexSimple2">Master-detail</a>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Uredaj" asp-action="Index">Uređaji</a>
            </div>
        </div>
    </div>
</div>

<div class="row ">
    <div class="col-md-8">

    </div>

    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="ObjektPdf">Ispis u pdf</a>
    </div>
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="ObjektExcel">Ispis u excel</a>
    </div>
</div>



<div class="jumbotron">
    <table class="table" id="objektTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Lokacija)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdDioniceNavigation.Naziv) Dionice
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.IdVrsteObjektaNavigation.Vrsta) Objekta
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="Uredaj" asp-action="Index" asp-route-objektId="@item.Id">@Html.DisplayFor(modelItem => item.Naziv)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Lokacija)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdDioniceNavigation.Kraj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdVrsteObjektaNavigation.Vrsta)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


@section scripts{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#objektTable').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        });
    </script>
}

Projekt/MojTimskiProjekt/Views/Objekt/IndexSimple.cshtml
@using MojTimskiProjekt.Models
@model MojTimskiProjekt.ViewModels.ObjektiViewModel

@{
    ViewData["Title"] = "IndexSimple";
    IEnumerable<Dionica> dionice = ViewData["dionice"] as IEnumerable<Dionica>;
}
<p></p>

<h3>Prikaz objekata</h3>

<br />

<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Create">Dodaj novi objekt</a>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Objekt" asp-action="Index">Natrag na listu</a>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron">



    <table class="table table-sm table-striped table-hover" id="objektTable">
        <thead>
            <tr>
                @{
                    string[] nazivi = { "Naziv", "Lokacija", "IdDionice", "IdVrsteObjekta" };
                    for (int i = 1; i <= nazivi.Length; i++)
                    {
                        <th>

                            @nazivi[i - 1]

                        </th>
                    }
                }
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var objekt in Model.Objekti)
            {
                <partial name="Row" model="objekt" />
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script type="text/javascript">
    $(function () {
        SetEditAjax(".editajax", '@Url.Action("EditPartial")', 'idobjekta');
        SetDeleteAjax(".deleteajax", '@Url.Action("DeletePartial")', 'idobjekta');
    });
    </script>

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#objektTable').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        });
    </script>
}