Projekt/MojTimskiProjekt/Areas/Autocomplete/Models/Upravitelj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace MojTimskiProjekt.Areas.Autocomplete.Models
{

    [DataContract]
    public class Upravitelj
    {
        [DataMember(Name = "label")]
        public string Label { get; set; }
        [DataMember(Name = "id")]
        public int Id { get; set; }
        public Upravitelj() { }
        public Upravitelj(int id, string label)
        {
            Id = id;
            Label = label;
        }
    }

}

Projekt/MojTimskiProjekt/Models/Upravitelj.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MojTimskiProjekt.Models
{
    public partial class Upravitelj
    {
        public Upravitelj()
        {
            Autocesta = new HashSet<Autocesta>();
            Obavijest = new HashSet<Obavijest>();
            Scenarij = new HashSet<Scenarij>();
            Zaposlenik = new HashSet<Zaposlenik>();
        }
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Naziv je obavezan")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Sjedište je obavezno")]
        public string Sjediste { get; set; }
        [Required(ErrorMessage = "OIB je Obavezan")]
        public int Oib { get; set; }
        [EmailAddress(ErrorMessage = "Neispravna e-mail adresa")]
        public string EMail { get; set; }
        [Required(ErrorMessage = "Kontakt je obavezan")]
        public int Kontakt { get; set; }

        public ICollection<Autocesta> Autocesta { get; set; }
        public ICollection<Obavijest> Obavijest { get; set; }
        public ICollection<Scenarij> Scenarij { get; set; }
        public ICollection<Zaposlenik> Zaposlenik { get; set; }
    }
}

Projekt/MojTimskiProjekt/ViewModels/UpraviteljViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using MojTimskiProjekt.Models;

namespace MojTimskiProjekt.ViewModels
{
    public class UpraviteljViewModel
    {
        public int Id { get; set; }

        public string Naziv { get; set; }
        public string Sjediste { get; set; }
        public string Oib { get; set; }
        public string EMail { get; set; }
        public string Kontakt { get; set; }

       
    }
}

Projekt/MojTimskiProjekt/ViewModels/ZaposleniciViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MojTimskiProjekt.ViewModels
{
    public class ZaposleniciViewModel
    {

        public IEnumerable<ZaposlenikViewModel> Zaposlenici { get; set; }

    }
}

Projekt/MojTimskiProjekt/Areas/Autocomplete/Controllers/UpraviteljController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MojTimskiProjekt.Areas.Autocomplete.Models;
using MojTimskiProjekt.Models;

namespace MojTimskiProjekt.Areas.Autocomplete.Controllers
{

    [Route("autocomplete/[controller]")]
    public class UpraviteljController : Controller
    {
        private readonly RPPP14Context ctx;
        private readonly AppSettings appData;

        public UpraviteljController(RPPP14Context ctx, IOptionsSnapshot<AppSettings> options)
        {
            this.ctx = ctx;
            appData = options.Value;
        }

        [HttpGet]
        public IEnumerable<IdLabel> Get(string term)
        {
            var query = ctx.Upravitelj
            .Select(m => new IdLabel
            {
                Id = m.Id,
                Label = m.Naziv
            })
            .Where(l => l.Label.Contains(term));

            var list = query.OrderBy(l => l.Label)
            .ThenBy(l => l.Id)
            .Take(appData.AutoCompleteCount)
           .ToList();
            return list;
        }
    }
}

Projekt/MojTimskiProjekt/Controllers/UpraviteljController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MojTimskiProjekt.Extensions;
using MojTimskiProjekt.Models;
using MojTimskiProjekt.ViewModels;
using Newtonsoft.Json;

namespace MojTimskiProjekt.Controllers
{
    public class UpraviteljController : Controller
    {
        private readonly RPPP14Context _context;
        private readonly AppSettings appData;
        private readonly ILogger logger;

        public UpraviteljController(RPPP14Context context, IOptionsSnapshot<AppSettings> options, ILogger<UpraviteljController> logger)
        {
            _context = context;
            appData = options.Value;
            this.logger = logger;
        }

        // GET: Upravitelj
        public IActionResult Index()
        {
            var upravitelji = _context.Upravitelj.AsNoTracking().OrderBy(a => a.Id).ToList();
            return View("Index", upravitelji);
        }

        public IActionResult IndexSimple()
        {
            var upravitelji = _context.Upravitelj
                .AsNoTracking()
                .Select(m => new UpraviteljViewModel
                {
                    Id = m.Id,
                    Naziv = m.Naziv,
                    Sjediste = m.Sjediste,
                    Oib = m.Oib.ToString(),
                    EMail = m.EMail,
                    Kontakt = m.Kontakt.ToString()
                })
                .ToList();
            var model = new UpraviteljiViewModel
            {
                Upravitelji = upravitelji
            };
            var autoceste = _context.Autocesta
                   .AsNoTracking()
                   .ToList();
            ViewData["autoceste"] = autoceste;
            logger.LogInformation("Učitavanje podataka o upraviteljima");
            return View(model);
        }


        public IActionResult IndexSimple2()
        {
            var upravitelji = _context.Upravitelj
                .AsNoTracking()
                .OrderBy(a => a.Id)
                .ToList();
            var autoceste = _context.Autocesta
                    .AsNoTracking()
                    .OrderBy(a => a.Naziv)
                    .ToList();

            ViewData["autoceste"] = autoceste;
            return View(upravitelji);
        }

        // GET: Upravitelj/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upravitelj = await _context.Upravitelj
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upravitelj == null)
            {
                return NotFound();
            }

            return View(upravitelj);
        }

        // GET: Upravitelj/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Upravitelj/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Sjediste,Oib,EMail,Kontakt")] Upravitelj upravitelj)
        {
            logger.LogTrace(JsonConvert.SerializeObject(upravitelj));
            if (ModelState.IsValid && !UpraviteljExists(upravitelj.Id))
            {
                try
                {
                    _context.Add(upravitelj);
                    await _context.SaveChangesAsync();
                    ViewData["message"] = $"Upravitelj {upravitelj.Naziv} je dodan u bazu";
                    logger.LogInformation(new EventId(1000), $"Upravitelj {upravitelj.Naziv} je dodan u bazu");
                    return RedirectToAction(nameof(Index), ViewData["message"]);
                }
                catch (Exception exc)
                {
                    logger.LogError("Pogreška prilikom dodavanje novog upravitelja: {0}", exc.CompleteExceptionMessage());
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return View(upravitelj);
                }
            }
            return View(upravitelj);
        }

        // GET: Upravitelj/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upravitelj = await _context.Upravitelj.FindAsync(id);
            if (upravitelj == null)
            {
                return NotFound();
            }
            return View(upravitelj);
        }

        // POST: Upravitelj/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Sjediste,Oib,EMail,Kontakt")] Upravitelj upravitelj)
        {
            if (id != upravitelj.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(upravitelj);
                    await _context.SaveChangesAsync();
                    logger.LogInformation($"Upravitelj {upravitelj.Naziv} je ažuriran");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UpraviteljExists(upravitelj.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(upravitelj);
        }

        // GET: Upravitelj/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upravitelj = await _context.Upravitelj
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upravitelj == null)
            {
                return NotFound();
            }

            return View(upravitelj);
        }

        // POST: Upravitelj/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var upravitelj = await _context.Upravitelj.FindAsync(id);
            if (upravitelj != null)
            {
                try
                {
                    _context.Upravitelj.Remove(upravitelj);
                    await _context.SaveChangesAsync();
                    logger.LogInformation($"Upravitelj {upravitelj.Naziv} uspješno obrisan");
                }
                catch (Exception exc)
                {
                    logger.LogError("Pogreška prilikom brisanja upravitelja: " + exc.CompleteExceptionMessage());
                }
            }
            else
            {
                logger.LogWarning("Ne postoji upravitelj s id-em: {0} ", id);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool UpraviteljExists(int id)
        {
            return _context.Upravitelj.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult EditPartial(int id)
        {
            var upravitelj = _context.Upravitelj
                             .AsNoTracking()
                             .Where(m => m.Id == id)
                             .SingleOrDefault();
            if (upravitelj != null)
            {

                return PartialView(upravitelj);
            }
            else
            {
                return NotFound($"Neispravan id upravitelja: {id}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPartial(Upravitelj upravitelj)
        {
            if (upravitelj == null)
            {
                return NotFound("Nema poslanih podataka");
            }
            bool checkId = _context.Zaposlenik.Any(m => m.Id == upravitelj.Id);
            if (!checkId)
            {
                return NotFound($"Neispravan id upravitelja: {upravitelj.Id}");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(upravitelj);
                    _context.SaveChanges();
                    logger.LogInformation(new EventId(1000), $"Upravitelj {upravitelj.Naziv} je ažuriran");
                    return StatusCode(302, Url.Action(nameof(Row), new { id = upravitelj.Id }));
                }
                catch (Exception exc)
                {
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return PartialView(upravitelj);
                }
            }
            else
            {
                return PartialView(upravitelj);
            }
        }

        public PartialViewResult Row(int id)
        {
            var upravitelj = _context.Upravitelj
                             .Where(m => m.Id == id)
                             .Select(m => new UpraviteljViewModel
                             {
                                 Id = m.Id,
                                 Naziv = m.Naziv,
                                 Sjediste = m.Sjediste,
                                 Oib = m.Oib.ToString(),
                                 EMail = m.EMail,

Projekt/MojTimskiProjekt/Views/Upravitelj/Create.cshtml
@model MojTimskiProjekt.Models.Upravitelj

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodavanje novog upravitelja</h2>

<h4>Upravitelj</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sjediste" class="control-label"></label>
                <input asp-for="Sjediste" class="form-control" />
                <span asp-validation-for="Sjediste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oib" class="control-label"></label>
                <input asp-for="Oib" class="form-control" />
                <span asp-validation-for="Oib" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kontakt" class="control-label"></label>
                <input asp-for="Kontakt" class="form-control" />
                <span asp-validation-for="Kontakt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

 <div class="col-md-5">
        <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Index">Natrag na Listu</a>
 </div>

Projekt/MojTimskiProjekt/Views/Upravitelj/Delete.cshtml
@model MojTimskiProjekt.Models.Upravitelj

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brisanje</h2>

<div>
    <h3>Upravitelj</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sjediste)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sjediste)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Oib)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Oib)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Kontakt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Kontakt)
        </dd>
    </dl>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <form asp-action="Delete" onclick="return confirm('Jeste li sigurni da želite obrisati?')">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Obriši" class="btn btn-danger delete" /> |
                </form>
            </div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Index">Natrag na listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/Upravitelj/Details.cshtml
@model MojTimskiProjekt.Models.Upravitelj

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalji</h2>

<div>
    <h3>Upravitelj</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sjediste)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sjediste)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Oib)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Oib)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Kontakt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Kontakt)
        </dd>
    </dl>
</div>
<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-action="Edit" asp-route-id="@Model.Id">Uredi</a>
            </div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Index">Natrag na Listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/Upravitelj/Edit.cshtml
@model MojTimskiProjekt.Models.Upravitelj

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Uređivanje</h2>

<h3>Upravitelj</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sjediste" class="control-label"></label>
                <input asp-for="Sjediste" class="form-control" />
                <span asp-validation-for="Sjediste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oib" class="control-label"></label>
                <input asp-for="Oib" class="form-control" />
                <span asp-validation-for="Oib" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kontakt" class="control-label"></label>
                <input asp-for="Kontakt" class="form-control" />
                <span asp-validation-for="Kontakt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-success btn-lg" />
            </div>
        </form>
    </div>
</div>
<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Index">Natrag na Listu</a>
            </div>
        </div>
    </div>
</div>

Projekt/MojTimskiProjekt/Views/Upravitelj/EditPartial.cshtml
@model MojTimskiProjekt.Models.Upravitelj

<tr>
    <td>
        <input asp-for="Naziv" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="Sjediste" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="Oib" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="EMail" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="Kontakt" class="form-control" data-save="" />
    </td>

    <td>
        <button type="submit" class="btn btn-sm btn-primary save" title="Spremi"><i class="fas fa-save">Spremi</i></button>
    </td>
    <td>
        <button class="btn btn-sm cancel" title="Odustani"><i class="fas fa-undo-alt">Odustani</i></button>
    </td>
</tr>
<tr>
    <td colspan="6">
        <div asp-validation-summary="All"></div>
        <input type="hidden" asp-for="Id" data-save="" />
    </td>
</tr>

Projekt/MojTimskiProjekt/Views/Upravitelj/IndexSimple.cshtml
@using MojTimskiProjekt.Models
@model MojTimskiProjekt.ViewModels.UpraviteljiViewModel

@{
    ViewData["Title"] = "IndexSimple";
    IEnumerable<Autocesta> autoceste = ViewData["autoceste"] as IEnumerable<Autocesta>;
}
<p></p>

<h3>Prikaz upravitelja</h3>

<br />

<div>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Create">Dodaj novog upravitelja</a>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <a class="btn btn-lg btn-primary  col-md-5 btn-block" asp-area="" asp-controller="Upravitelj" asp-action="Index">Natrag na listu</a>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron">



    <table class="table table-sm table-striped table-hover">
        <thead>
            <tr>
                @{
                    string[] nazivi = { "Naziv", "Sjediste", "Oib", "EMail", "Kontakt", "Autoceste" };
                    for (int i = 1; i <= nazivi.Length; i++)
                    {
                        <th>

                            @nazivi[i - 1]

                        </th>
                    }
                }
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var upravitelj in Model.Upravitelji)
            {
                <partial name="Row" model="upravitelj" />
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
            SetEditAjax(".editajax", '@Url.Action("EditPartial")','idupravitelja');
            SetDeleteAjax(".deleteajax", '@Url.Action("DeletePartial")', 'idupravitelja');
        });
    </script>
}

Projekt/MojTimskiProjekt/Views/Upravitelj/IndexSimple2.cshtml
@using MojTimskiProjekt.Models
@model IEnumerable<MojTimskiProjekt.Models.Upravitelj>

@{
    ViewData["Title"] = "IndexSimple2";
    IEnumerable<Autocesta> autoceste = ViewData["autoceste"] as IEnumerable<Autocesta>;
}

<h2>Prikaz upravitelja s pripadajućim autocestama</h2>
<br/>

<div class="row ">

    <div class="col-md-8">

    </div>

    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="UpraviteljiPdf">Ispis u pdf</a>
    </div>
    <div class="col-md-2">
        <a class="btn btn-md btn-block btn-info" asp-controller="Report" asp-action="UpraviteljiExcel">Ispis u excel</a>
    </div>

</div>
<div class="jumbotron">


    <table class="table" id="upraviteljTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sjediste)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Oib)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EMail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kontakt)
                </th>
                <th>
                    Autoceste
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sjediste)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Oib)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EMail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kontakt)
                </td>
                <td>
                    @{
                        foreach (Autocesta autocesta in autoceste)
                        {
                            if (autocesta != null && autocesta.IdUpravitelja == item.Id)
                            {

                                @Html.DisplayFor(modelItem => autocesta.Naziv)

                                <br />

                            }

                        }
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Projekt/MojTimskiProjekt/Views/Upravitelj/Row.cshtml
@model MojTimskiProjekt.ViewModels.UpraviteljViewModel
@{
    IEnumerable<Autocesta> autoceste = ViewData["autoceste"] as IEnumerable<Autocesta>;

}
<tr>

    <td class="text-left">@Model.Naziv</td>
    <td class="text-left">@Model.Sjediste</td>
    <td class="text-left">@Model.Oib</td>
    <td class="text-left">@Model.EMail</td>
    <td class="text-left">@Model.Kontakt</td>
    <td class="textt-left">
        @{
            foreach (var autocesta in autoceste)
            {
                if (autocesta != null && autocesta.IdUpravitelja == Model.Id)
                {

                    @Html.DisplayFor(modelItem => autocesta.Naziv)

                    <br />

                }

            }
        }
    </td>

    <td>
        <a data-idupravitelja="@Model.Id" class="btn btn-sm editajax btn-success" title="Ažuriraj"><i class="fas fa-edit">Ažuriraj</i></a>
    </td>
    <td>
        <form asp-action="Delete" method="post">
            @*Neće se koristiti direktni submit, ali treba zbog anti forgery tokena*@
            @*Jednako tako nije potreban ni ovaj input type=hidden ako skripta ispravno radi*@
            <input type="hidden" name="id" value="@Model.Id" />
            <button data-idupravitelja="@Model.Id" class="btn btn-sm btn-danger deleteajax" title="Obriši"><i class="fas fa-trash-alt">Obriši</i></button>
        </form>
    </td>

</tr>


@section scripts{
    <script type="text/javascript">
        $(function () {
            SetEditAjax(".editajax", '@Url.Action("EditPartial")','idupravitelja');
            SetDeleteAjax(".deleteajax", '@Url.Action("Delete")', 'idupravitelja');
        });
    </script>


}